---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - image: prom/blackbox-exporter:latest
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          protocol: TCP
        resources:
          limits:
            memory: 512Mi 
          requests:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  ports:
    - port: 9115
      targetPort: 9115
      name: blackbox-exporter-service
  selector:
    app: blackbox-exporter
