Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.56.27"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, autocorrect: true
  config.vm.network "forwarded_port", guest: 3000, host: 3000, autocorrect: true
  config.vm.network "forwarded_port", guest: 30000, host: 30000, autocorrect: true
  config.vm.network "forwarded_port", guest: 80, host: 80, autocorrect: true
  config.vm.network "forwarded_port", guest: 9090, host: 9090, autocorrect: true
  config.vm.network "forwarded_port", guest: 2379, host: 2379, autocorrect: true
  config.vm.network "forwarded_port", guest: 2380, host: 2380, autocorrect: true
  config.vm.network "forwarded_port", guest: 2380, host: 2380, autocorrect: true
  config.vm.network "forwarded_port", guest: 443, host: 443, autocorrect: true
  config.vm.network "forwarded_port", guest: 10250, host: 10250, autocorrect: true
  config.vm.network "forwarded_port", guest: 10259, host: 10259, autocorrect: true
  config.vm.network "forwarded_port", guest: 10257, host: 10257, autocorrect: true
  config.vm.network "forwarded_port", guest: 9200, host: 9200, autocorrect: true
  config.vm.network "forwarded_port", guest: 9300, host: 9300, autocorrect: true
  config.vm.network "forwarded_port", guest: 3100, host: 3100, autocorrect: true
  config.vm.network "forwarded_port", guest: 5601, host: 5601, autocorrect: true
  config.vm.network "forwarded_port", guest: 30000, host: 30000, autocorrect: true
  config.vm.usable_port_range =  30000..32767
end
