Vagrant.configure("2") do |config|
   config.vm.box = "bento/ubuntu-20.04"
   config.vm.network "private_network", ip: "192.168.56.2"
   config.vm.network "forwarded_port", guest: 8080, host: 8080, autocorrect: true
   config.vm.network "forwarded_port", guest: 80, host: 80, autocorrect: true
   config.vm.network "forwarded_port", guest: 10050, host: 10050, autocorrect: true
   config.vm.network "forwarded_port", guest: 10051, host: 10051, autocorrect: true
   config.vm.network "forwarded_port", guest: 443, host: 443, autocorrect: true
   config.vm.network "forwarded_port", guest: 3306, host: 3306, autocorrect: true
   config.vm.network "forwarded_port", guest: 5432, host: 5432, autocorrect: true
   config.vm.provision "file", source: "bashrc", destination: "~/vm_conf_files/bashrc"
   config.vm.provision :shell, path: "setup.sh"
   config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "labmonitoring"
      vb.memory = "4096"
   end
end
