Vagrant.configure("2") do |config|
   config.vm.box = "bento/ubuntu-20.04"
   config.vm.network "private_network", ip: "192.168.56.31"
   config.vm.network "forwarded_port", guest: 8080, host: 8080, autocorrect: true
   config.vm.network "forwarded_port", guest: 80, host: 80, autocorrect: true
   config.vm.network "forwarded_port", guest: 25, host: 25, autocorrect: true
   config.vm.network "forwarded_port", guest: 587, host: 587, autocorrect: true
   config.vm.network "forwarded_port", guest: 443, host: 443, autocorrect: true
   config.vm.network "forwarded_port", guest: 3000, host: 3000, autocorrect: true
   config.vm.network "forwarded_port", guest: 15672, host: 15672, autocorrect: true
   config.vm.network "forwarded_port", guest: 9200, host: 9200, autocorrect: true
   config.vm.network "forwarded_port", guest: 9300, host: 9300, autocorrect: true
   config.vm.network "forwarded_port", guest: 5601, host: 5601, autocorrect: true
   config.vm.network "forwarded_port", guest: 3306, host: 3306, autocorrect: true
   config.vm.network "forwarded_port", guest: 5432, host: 5432, autocorrect: true
   config.vm.provision "file", source: "bashrc", destination: "~/vm_conf_files/bashrc"
   config.vm.provision :shell, path: "bootstrap.sh"
   config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "labmonitoring"
      vb.memory = "4096"
   end
end
