Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, autocorrect: true
  config.vm.network "forwarded_port", guest: 80, host: 80, autocorrect: true
  config.vm.network "forwarded_port", guest: 2379, host: 2379, autocorrect: true
  config.vm.network "forwarded_port", guest: 2380, host: 2380, autocorrect: true
  config.vm.network "forwarded_port", guest: 2380, host: 2380, autocorrect: true
  config.vm.network "forwarded_port", guest: 443, host: 443, autocorrect: true
  config.vm.network "forwarded_port", guest: 10250, host: 10250, autocorrect: true
  config.vm.network "forwarded_port", guest: 10259, host: 10259, autocorrect: true
  config.vm.network "forwarded_port", guest: 10257, host: 10257, autocorrect: true
  #config.vm.usalble_port_range "forwarded_port" 30000..32767, guest: , host: 30000..32767, autocorrect: true
  config.vm.provision "shell", path: "setup.sh"
end
